// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ10cCE8JUS0TJqSjhGbBclsxshDj8DzA',
    appId: '1:126791694077:web:21edef631676a95106b094',
    messagingSenderId: '126791694077',
    projectId: 'appquanlychitieu-70b3f',
    authDomain: 'appquanlychitieu-70b3f.firebaseapp.com',
    storageBucket: 'appquanlychitieu-70b3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA90EVQ4-AzkFBMeiwXZplojgORcDb_71Q',
    appId: '1:126791694077:android:2d3067be603d269d06b094',
    messagingSenderId: '126791694077',
    projectId: 'appquanlychitieu-70b3f',
    storageBucket: 'appquanlychitieu-70b3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHt3XOLARp079z_85AcWiNaNNxSbpgIs',
    appId: '1:126791694077:ios:48e6deb3b594d23f06b094',
    messagingSenderId: '126791694077',
    projectId: 'appquanlychitieu-70b3f',
    storageBucket: 'appquanlychitieu-70b3f.firebasestorage.app',
    iosBundleId: 'com.example.quanlychitieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdHt3XOLARp079z_85AcWiNaNNxSbpgIs',
    appId: '1:126791694077:ios:48e6deb3b594d23f06b094',
    messagingSenderId: '126791694077',
    projectId: 'appquanlychitieu-70b3f',
    storageBucket: 'appquanlychitieu-70b3f.firebasestorage.app',
    iosBundleId: 'com.example.quanlychitieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ10cCE8JUS0TJqSjhGbBclsxshDj8DzA',
    appId: '1:126791694077:web:3505e718302fd92f06b094',
    messagingSenderId: '126791694077',
    projectId: 'appquanlychitieu-70b3f',
    authDomain: 'appquanlychitieu-70b3f.firebaseapp.com',
    storageBucket: 'appquanlychitieu-70b3f.firebasestorage.app',
  );
}
